### ISSUE TITLE
Getting 'too many requests' error from nubank after some request/ Recebendo 'too many requests' do nubank depois de realizar algumas requisições

### ISSUE THREAD

**Issue by othecos** [Astrocoders/nubank-api#4]
Hello, i was trying to test the methods and after like 5 or 6 tests, i started to receive `{error: too many requests}`  and i can no longer acess my account. Do you know how can i pass through this?

Olá, eu estava testando os metodos da sua API, mas após alguns testes, uns 5 ou 6, começei a receber `{error: too many requests}`  e meu acesso a conta foi bloqueado, voce sabe como eu poderia resolver isso?

**Comment by fakenickels** [comment]
I think you can probably just await a bit before trying again or reach NuBank Twitter support

**Comment by othecos** [comment]
So, i figure out what it was the problem.

The problem was that i was trying to log in multiple times in the same session, so, probably, Nubank saw that as an attack, and then blocked my account. After discovering that, the solution was pretty obvious. I can only log in to the account once per session, dããr.

Obs: I'll close this issue because it was resolved.
