### ISSUE TITLE
New QRCode requirement

### ISSUE THREAD

**Issue by arthurnobrega** [Astrocoders/nubank-api#6]
Hello!

I noticed that Nubank started asking for a QRCode on the online site to give access to the API, which made our strategy of accessing the API to break.

Can you test if it's working for you?

Do you have any idea how to work around after this change?

**Comment by fakenickels** [comment]
Hey there!
We haven't putting effort on it actually lately, so it's probably not working indeed.
I saw there someone did a port to python of it so it may be more up-to-date than ours
https://github.com/andreroggeri/pynubank.
