### ISSUE TITLE
ERR_BAD_SSL_CLIENT_AUTH_CERT

### ISSUE THREAD

**Issue by robledoleonardo** [Astrocoders/nubank-api#8]
request.js?af32:150 OPTIONS https://prod-auth.nubank.com.br/api/token net::ERR_BAD_SSL_CLIENT_AUTH_CERT

**Comment by guilhermedecampo** [comment]
hey @robledoleonardo 	you should take a look on https://github.com/andreroggeri/pynubank
guys are ahead us here on the verifications auth etc

**Comment by fakenickels** [comment]
yea we are not providing support here anymore
